Exercise 11.18 dep success hook test

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -14,6 +14,7 @@ on:
 
 jobs:
   CI:
+    # PR status check will hang if #no-ci is in the title -> force merge only in tests
     if: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.title, '#no-ci') }}
     runs-on: ubuntu-24.04
     steps:
@@ -68,8 +69,8 @@ jobs:
       }}
     runs-on: ubuntu-24.04
     steps:
-      - name: Faile fast for hook test
-        run: exit 1
+      # - name: Fail fast for hook test
+      #   run: exit 1
       # Deploy to Render
       - name: Trigger deployment
         run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
